language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t diaboloshogunate/react-ci:latest -f .
script:
  - docker run -e CI=true diaboloshogunate/react-ci:latest npm test -- --coverage